// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import BenchmarkRecipeController from "./benchmark_recipe_controller"
application.register("benchmark-recipe", BenchmarkRecipeController)

import CascadingSelectController from "./cascading_select_controller"
application.register("cascading-select", CascadingSelectController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import DisclosureController from "./disclosure_controller"
application.register("disclosure", DisclosureController)

import FileDropController from "./file_drop_controller"
application.register("file-drop", FileDropController)

import HeatmapController from "./heatmap_controller"
application.register("heatmap", HeatmapController)

import HostnameValidationController from "./hostname_validation_controller"
application.register("hostname-validation", HostnameValidationController)

import ImageViewerController from "./image_viewer_controller"
application.register("image-viewer", ImageViewerController)

import LogStreamController from "./log_stream_controller"
application.register("log-stream", LogStreamController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationItemController from "./notification_item_controller"
application.register("notification-item", NotificationItemController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import RackDiagramController from "./rack_diagram_controller"
application.register("rack-diagram", RackDiagramController)

import ReleaseModeController from "./release_mode_controller"
application.register("release-mode", ReleaseModeController)

import ServerProductSearchController from "./server_product_search_controller"
application.register("server-product-search", ServerProductSearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SlideOverController from "./slide_over_controller"
application.register("slide-over", SlideOverController)

import SshProfileSelectController from "./ssh_profile_select_controller"
application.register("ssh-profile-select", SshProfileSelectController)

import SshSettingsController from "./ssh_settings_controller"
application.register("ssh-settings", SshSettingsController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import WizardController from "./wizard_controller"
application.register("wizard", WizardController)
