// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import AutoRefreshController from "./auto_refresh_controller"
application.register("auto-refresh", AutoRefreshController)

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import BenchmarkRecipeController from "./benchmark_recipe_controller"
application.register("benchmark-recipe", BenchmarkRecipeController)

import BulkReviewController from "./bulk_review_controller"
application.register("bulk-review", BulkReviewController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import CascadingSelectController from "./cascading_select_controller"
application.register("cascading-select", CascadingSelectController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import DisclosureController from "./disclosure_controller"
application.register("disclosure", DisclosureController)

import FileDropController from "./file_drop_controller"
application.register("file-drop", FileDropController)

import HeatmapController from "./heatmap_controller"
application.register("heatmap", HeatmapController)

import HostnameAutocompleteController from "./hostname_autocomplete_controller"
application.register("hostname-autocomplete", HostnameAutocompleteController)

import HostnameValidationController from "./hostname_validation_controller"
application.register("hostname-validation", HostnameValidationController)

import ImageViewerController from "./image_viewer_controller"
application.register("image-viewer", ImageViewerController)

import LogStreamController from "./log_stream_controller"
application.register("log-stream", LogStreamController)

import MlcProfileController from "./mlc_profile_controller"
application.register("mlc-profile", MlcProfileController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationItemController from "./notification_item_controller"
application.register("notification-item", NotificationItemController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PageRefreshController from "./page_refresh_controller"
application.register("page-refresh", PageRefreshController)

import RackDiagramController from "./rack_diagram_controller"
application.register("rack-diagram", RackDiagramController)

import RackValidationController from "./rack_validation_controller"
application.register("rack-validation", RackValidationController)

import ReleaseModeController from "./release_mode_controller"
application.register("release-mode", ReleaseModeController)

import ServerProductSearchController from "./server_product_search_controller"
application.register("server-product-search", ServerProductSearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SlideOverController from "./slide_over_controller"
application.register("slide-over", SlideOverController)

import SshOverrideController from "./ssh_override_controller"
application.register("ssh-override", SshOverrideController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import WizardController from "./wizard_controller"
application.register("wizard", WizardController)
