---
- name: Enable and start salt-master
  ansible.builtin.systemd:
    name: salt-master
    state: started
    enabled: true

- name: Enable and start salt-api
  ansible.builtin.systemd:
    name: salt-api
    state: started
    enabled: true
