[salt_master]
salt-master-01  ansible_host=192.168.127.128

[salt_minions]
salt-minion-01  ansible_host=192.168.127.129

[all:vars]
ansible_user=reidlin
ansible_ssh_private_key_file=~/.ssh/id_ed25519

